### ISSUE TITLE
How download torrent works?

### ISSUE THREAD

**Issue by adocampo** [jsavargas/telethon_downloader#64]
I've tried to figure how torrent download works, but I have no idea. It seems it works with transmission, but I don't know how it would connect to it.

I've moved a .torrent file to the watch directory, but nothing appears on the telethon_downloader logs...

Am I missing something? I guessed the "torrent download" functionality means if I put a .torrent in that folder, it will send it to transmission, but as far as I can see, there isn't such functionality, just share the `/watch` directory among this docker and transmission docker... I guess there are TG channels sharing .torrent files and this is a quick workaround to send those torrents from TG to the torrent client?

**Comment by jsavargas** [comment]
correct, what it does is that you send a torrent file (.torrent) to the telegram bot and it leaves it in /watch, so that your torrent client can take it from that path and start downloading, perhaps the name torrent download is tricky, but it's a way to default .torrents to be downloaded to /watch.

If you have more questions about how to integrate it into your torrent client, let me know
